language: ruby
rvm:
  - 2.0.0
cache: bundler
script:
  - RAILS_ENV=test bundle exec rake
before_script:
  - RAILS_ENV=test bundle exec rake db:schema:load
  - RAILS_ENV=test bundle exec rake db:test:prepare
